name: Auto Commit Changes

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure clean state
        run: git reset --hard

      - name: Make changes
        run: |
          echo "Automated commit at $(date)" >> auto_commit_log.txt

      - name: Commit changes
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Automated commit at $(date)"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
